use crate::ui::{drawable::Drawable, event::UiAction, event::UiEvent, event::UiEventOutcome};
use rustc_hash::FxHashMap;
use uuid::Uuid;

/// Identifier for nodes in the UI workspace.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NodeId(Uuid);

impl NodeId {
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

/// Context passed to views during build; collects drawables.
pub struct ViewContext<'a> {
    drawables: &'a mut Vec<Drawable>,
    current_layer: i32,
}

impl<'a> ViewContext<'a> {
    pub fn push(&mut self, drawable: Drawable) {
        self.drawables.push(drawable);
    }

    pub fn with_layer(&mut self, layer: i32) -> ViewContext<'_> {
        ViewContext {
            drawables: self.drawables,
            current_layer: layer,
        }
    }

    pub fn layer(&self) -> i32 {
        self.current_layer
    }
}

/// Trait implemented by UI views to emit drawables.
pub trait UiView {
    fn build(&mut self, ctx: &mut ViewContext);
    fn handle_event(&mut self, _evt: &UiEvent) -> UiEventOutcome {
        UiEventOutcome::none()
    }
}

struct Node {
    view: Box<dyn UiView>,
    children: Vec<NodeId>,
}

/// Node-driven UI workspace: holds a tree of views and produces drawables.
pub struct Workspace {
    nodes: FxHashMap<NodeId, Node>,
    roots: Vec<NodeId>,
    dirty: bool,
    pending_actions: Vec<UiAction>,
}

impl Workspace {
    pub fn new() -> Self {
        Self {
            nodes: FxHashMap::default(),
            roots: Vec::new(),
            dirty: true,
            pending_actions: Vec::new(),
        }
    }

    /// Insert a view as a new node and return its id.
    pub fn add_view<V: UiView + 'static>(&mut self, view: V) -> NodeId {
        let id = NodeId::new();
        self.nodes.insert(
            id,
            Node {
                view: Box::new(view),
                children: Vec::new(),
            },
        );
        id
    }

    /// Mark a node as a root in the workspace.
    pub fn add_root(&mut self, id: NodeId) {
        if self.nodes.contains_key(&id) && !self.roots.contains(&id) {
            self.roots.push(id);
        }
    }

    /// Attach a child node under a parent.
    pub fn attach(&mut self, parent: NodeId, child: NodeId) {
        let child_exists = self.nodes.contains_key(&child);
        if child_exists {
            if let Some(p) = self.nodes.get_mut(&parent) {
                if !p.children.contains(&child) {
                    p.children.push(child);
                }
            }
        }
    }

    /// Traverse roots and collect drawables.
    pub fn build(&mut self) -> Vec<Drawable> {
        let mut drawables = Vec::new();
        let roots = self.roots.clone();
        for root in roots {
            self.build_node(root, &mut drawables, 0);
        }
        self.dirty = false;
        drawables
    }

    fn build_node(&mut self, id: NodeId, out: &mut Vec<Drawable>, layer: i32) {
        let Some(node) = self.nodes.get_mut(&id) else {
            return;
        };
        let mut ctx = ViewContext {
            drawables: out,
            current_layer: layer,
        };
        node.view.build(&mut ctx);
        for child in node.children.clone() {
            self.build_node(child, out, layer);
        }
    }

    /// Dispatch a UI event to all views; collects actions and marks dirty when a view changes.
    pub fn handle_event(&mut self, evt: &UiEvent) {
        let mut outcome = UiEventOutcome::none();
        let roots = self.roots.clone();
        for root in roots {
            outcome.merge(self.dispatch_node(root, evt));
        }
        if outcome.dirty {
            self.dirty = true;
        }
        if !outcome.actions.is_empty() {
            self.pending_actions.extend(outcome.actions);
        }
    }

    fn dispatch_node(&mut self, id: NodeId, evt: &UiEvent) -> UiEventOutcome {
        let mut merged = UiEventOutcome::none();
        if let Some(node) = self.nodes.get_mut(&id) {
            merged.merge(node.view.handle_event(evt));
            let children = node.children.clone();
            for child in children {
                merged.merge(self.dispatch_node(child, evt));
            }
        }
        merged
    }

    /// Returns whether any view changed state since the last build.
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }

    /// Drain and return pending UI actions generated by views.
    pub fn take_actions(&mut self) -> Vec<UiAction> {
        std::mem::take(&mut self.pending_actions)
    }
}
